### PR TITLE
Fix rejected cloudwatch metric with empty tag

### LINKED ISSUE #1813: CloudWatchMeterRegistry sends tags with empty values which CloudWatch then rejects
Project reactor integration for instance defines an `exception` tag with a default value of "", for when collecting metrics for arbitrary sequences (`reactor.flow.duration`).

Similar to #1167

With the following workaround I can get the metrics to show up in CloudWatch:

```java
@Configuration
public class MetricsConfig {
  @Bean
  MeterRegistryCustomizer<CloudWatchMeterRegistry> sanitizeReactorTags() {
    return registry ->
        registry
            .config()
            .meterFilter(
                MeterFilter.replaceTagValues("exception", tag -> tag.isBlank() ? "None" : tag));
  }
}
```
^ I chose to turn the blank tag into "None", similar to how the Spring request latency metrics look like, but the tag could just as well be removed I guess.

### PR DESCRIPTION
**Pull request by carhartl**
CloudWatch rejects any metric with a dimension that has an empty value, which might cause unexpected loss of metrics. Reactor for instance produces metrics where the "exception" dimension may have an empty value, and thus those metrics do not show up in CloudWatch without a workaround.

Similar to how the InfluxMeterRegistry behaves (see #1166) we're dropping such a faulty dimension before sending off the data.

~Additionally dropping dimensions with values exceeding the maximum (255).~
EDIT: Additionally implementing a CloudWatch naming convention that ensures the maximum length for both key and value are adhered to (by truncating).

Reference:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html

Closes #1813

### CODE REVIEW

**Comment by carhartl** [comment]
Open question: did this for the cloudwatch2 implementation only, should it also be done for the  other (older?) cloudwatch implementation?

**Comment by shakuzen** [comment]
Thanks for the pull request. Would you be so kind as to rebase your changes on the `1.1.x` branch and target the pull request at that so we can get the fix into maintenance releases? I'll take care of merging it forward.

Related to your question, the cloudwatch2 implementation does not exist in the `1.1.x` branch. So the changes should be made for the older implementation, as we still support it in `1.1.x` even though it is deprecated in later releases. This is a good reminder to consider when we stop publishing the older implementation, though. So thank you for that.

File: implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java [hunk 1]
```diff
@@ -295,6 +296,10 @@ StandardUnit toStandardUnit(@Nullable String unit) {
 
         private List<Dimension> toDimensions(List<Tag> tags) {
             return tags.stream()
+                    // Take restrictions for dimensions in CloudWatch into account
+                    // https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html
+                    .filter(t -> StringUtils.isNotBlank(t.getValue()))
+                    .filter(t -> t.getValue().length() <= 255)
```
Comment (shakuzen) [inline implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java]: For maximum length constraints, we have historically truncated the tag value. We do this in a `NamingConvention` implementation that the MeterRegistry is configured to use.

File: implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java [hunk 2]
```diff
@@ -295,6 +296,10 @@ StandardUnit toStandardUnit(@Nullable String unit) {
 
         private List<Dimension> toDimensions(List<Tag> tags) {
             return tags.stream()
+                    // Take restrictions for dimensions in CloudWatch into account
+                    // https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html
+                    .filter(t -> StringUtils.isNotBlank(t.getValue()))
```
Comment (shakuzen) [inline implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java]: If we are dropping a tag, we could use our `WarnThenDebugLogger` to give some visibility to users that a tag is being dropped and for what reason. Otherwise, it may be too hard to notice and track down for users.

Comment (carhartl) [reply implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java]: The implementation feels a bit clumsy but since we're operating on a stream I did not have a better idea.

File: implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java (hunk 1 above)
Comment (carhartl) [reply implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java]: Done.

File: implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java [hunk 3]
```diff
@@ -149,6 +150,7 @@ public void onSuccess(PutMetricDataRequest request, PutMetricDataResult result)
     // VisibleForTesting
     class Batch {
         private long wallTime = clock.wallTime();
+        private WarnThenDebugLogger logger = new WarnThenDebugLogger(Batch.class);
```
Comment (shakuzen) [inline implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java]: I'd like to move this up to the CloudWatchMeterRegistry class, but I can take care of this in a follow-up polish commit.
