### PR TITLE
Declarative Annotation Based API for Counters

### LINKED ISSUE #1435: Declarative Annotation Based API for Counters
Synopsis
--------
Although using `Timer` and `DistributionSummary` we can publish a count of events in addition to other measurements, sometimes it just makes sense to use a plain `Counter`. 

For timers, in order to keep track of how long a particular task is running, we have two options:
 1. Manually starting and stopping the `Timer`.
 2. Declarative time tracking using the `@Timed`.

These two options are complementary to each other. That is, the declarative approach is there to abstract the cross-cutting concern in a nice and familiar enterprise-ish way but we still have the option to manually manage the `Timer`s when we can't use the declarative API.

_For plain `Counter`s, there is no such declarative approach._ 

Recurring Pattern
-------------------
It's a recurring theme to keep track of:
 - A total number of attempts for a particular task.
 - A number of successful attempts.
 - A Number of failed attempts.

For example. when I receive a job submission request, I increment the `job.submission.attempts` by one. If I managed to successfully submit the job, the `job.submission.successful` would be incremented by one. Otherwise, I'd increment the `job.submission.failed` metric.

Suggestion
------------
Alongside the current `Counter` API, we can provide a declarative API to manage counters. For example, we can offer an annotation, e.g. `@Counted`, as the entry point to such API:
```java
/**
 * We expose the following metrics for the methods annotated with this annotation:
 * <ul>
 *     <li>{@code metric.initialSuffix} to represent the number of times the method is executed</li>
 *     <li>{@code metric.succeedSuffix} to represent the number of successful executions.</li>
 *     <li>{@code metric.failedSuffix} to represent the number of failed executions.</li>
 * </ul>
 */
@Inherited
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Counted {

    /**
     * Determines the basic metric name, e.g. {@code job.submission}.
     * 
     * @return The prefix for all metrics.
     */
    String metric();

    /**
     * Determines the suffix for total attempts.
     * 
     * @return The total attempts suffix.
     */
    String initialSuffix() default "attempts";

    /**
     * Determines the suffix for successful attempts.
     * 
     * @return The successful attempts suffix.
     */
    String succeedSuffix() default "succeed";

    /**
     * Determines the suffix for failed attempts.
     *
     * @return The failed attempts suffix.
     */
    String failedSuffix() default "failed";
}
```

Then we can implement the counting logic using an aspect much like the `TimedAspect`:
```java
@Aspect
public class CountedAspect {

    private static final String EXCEPTION_TAG_NAME = "exception";
    
    private final MeterRegistry meterRegistry;

    public CountedAspect(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }
    
    @Around("@annotation(counted)")
    public Object interceptAndCount(ProceedingJoinPoint pjp, Counted counted) throws Throwable {
        try {
            Counter.builder(initialName(counted)).register(meterRegistry).increment();
            Object result = pjp.proceed();
            Counter.builder(successfulName(counted)).register(meterRegistry).increment();
            
            return result;
        } catch (Throwable e) {
            Counter.builder(failedName(counted))
                .tag(EXCEPTION_TAG_NAME, e.getClass().getSimpleName())
                .register(meterRegistry).increment();
                
            throw e;
        }
    }
    
    private String initialName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.initialSuffix());
    }

    private String successfulName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.succeedSuffix());
    }

    private String failedName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.failedSuffix());
    }
}
```

If you guys are OK with the idea, I'm more than happy to provide a PR.

Cheers 🍻

### PR DESCRIPTION
**Pull request by alimate**
A few points:
 - I thought there is no use case for making the `Counted` annotation a *Repeatable* one. If you guys think otherwise, please let me know.
 - Same argument for the `extraTags`. Are they useful for `Counted`?

Resolves #1435

### CODE REVIEW

File: micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+     */
+    String value() default "";
+
+    /**
+     * By default, successful attempts won't be recorded. Switch it to {@code true} in order to
+     * record successful attempts alongside with failed attempts.
+     *
+     * @return Whether to report successful attempts or not.
+     */
+    boolean successfulAttempts() default false;
```
Comment (checketts) [inline micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java]: I think defaulting this to true would be better. My comment on #1435 about defaulting to false was about the 'submitted' count (which you have eliminated)

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+        try {
+            Object result = pjp.proceed();
+            if (counted.successfulAttempts()) {
+                counter(pjp, counted).tag(STATUS_TAG, "succeed").register(meterRegistry).increment();
+            }
+
+            return result;
+        } catch (Throwable e) {
+            counter(pjp, counted)
+                    .tag(EXCEPTION_TAG, e.getClass().getSimpleName())
```
Comment (checketts) [inline micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: You can't have different tags for the same metric, so you'll need to add a blank `EXCEPTION_TAG` to the success counter

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+                    .tag(STATUS_TAG, "failed")
```
Comment (checketts) [inline micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: Since `succeed` and `failed` aren't grammatically parallel, I would recommend changing them to be similar to the tags used in [CaffeineCacheMetrics](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineCacheMetrics.java#L167): make the key `result` with `success`/`failure`

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java (hunk 2 above)
Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: 🙈 My bad!

File: micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java (hunk 1 above)
Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java]: Does it make sense to make this behavior configurable?

Comment (checketts) [reply micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java]: I could see that some users would want to `recordFailuresOnly`, if they only care about exceptions/failures. So I think there might be a good reason to have some configuration, but renaming it might be a good idea.

Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/annotation/Counted.java]: I've renamed to `recordFailuresOnly`, as you suggested.

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java (hunk 2 above)
Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: When recording successful attempts, I tag the metric with `None` exception. Is it OK?

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java (hunk 3 above)
Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: ✅

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+     * @param counted The annotation.
+     * @return Whatever the intercepted method returns.
+     * @throws Throwable When the intercepted method throws one.
+     */
+    @Around("@annotation(counted)")
+    public Object interceptAndRecord(ProceedingJoinPoint pjp, Counted counted) throws Throwable {
+        try {
+            Object result = pjp.proceed();
+            if (!counted.recordFailuresOnly()) {
+                record(pjp, counted, "None", "success");
```
Comment (checketts) [inline micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: Looks like the `@TimedAspect` used a lowercase `none`

Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: ✅

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java (hunk 2 above)
Comment (checketts) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: Make it lowercase so it is similar to the `@TimedAspect`

Comment (alimate) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: Done!

**Comment by checketts** [comment]
Anyone else want to look this over before merging? @jkschneider or @davidkarlsen (since you both contributed to the `@TimedAspect`)?

**Comment by alimate** [comment]
@checketts Is it a good idea to add a `result` tag to `TimedAspect`? I know we can infer the execution status by the `exception` tag but using something like a `result` tag would simplify the process.

**Comment by checketts** [comment]
Making them consistent wouldn't be a bad idea. Perhaps adding it in a separate PR would be a good idea so it doesn't distract the conversation in this PR.

File: micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java (hunk 4 above)
Comment (shakuzen) [reply micrometer-core/src/main/java/io/micrometer/core/aop/CountedAspect.java]: It is unfortunate that `WebMvcTags` in the Spring support uses `None`, though. We should probably align these in 2.0.
