### PR TITLE
Fix logic to remove Kafka meters with less tags

### LINKED ISSUE #2212: KafkaClientMetrics not working as expected (topic names missing etc.)
Hi all, we are currently upgrading from Spring Boot 2.2.7 to Spring Boot 2.3.1 and therewith we also want to start using the new KafkaClientMetrics using the FactoryListener from Spring Kafka.

However, we currently see that the **metrics do not contain all expected tags (like topic names etc.)** and that **not all topic-related metrics are provided for all topics**. 

In the example below you can see that we have only 3 metrics for the average lag (with topic names), the metrics for max lag do not contain topic names at all etc.

Any idea why this is the case? 

I would have expected to have all topic-related metrics with a topic name as a tag. Another service that we have upgraded to use the new KafkaClientMetrics only shows the max lag metrics (without topic names) and no other lag-related metrics at all-

```´
# HELP kafka_consumer_fetch_manager_records_lag_avg The average lag of the partition
# TYPE kafka_consumer_fetch_manager_records_lag_avg gauge
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-craft-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-0",topic="csm_local_referencedata_craft",} NaN
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",partition="1",spring_id="kafkaConsumerFactory.csm-cloud-project-1",topic="csm_local_projectmanagement_project_delete",} NaN
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-0",topic="csm_local_projectmanagement_project_delete",} NaN
# HELP kafka_consumer_fetch_manager_records_lag_max The maximum lag in terms of number of records for any partition in this window
# TYPE kafka_consumer_fetch_manager_records_lag_max gauge
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-0",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-0",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-0",} NaN
# HELP kafka_consumer_fetch_manager_records_lag The latest lag of the partition
# TYPE kafka_consumer_fetch_manager_records_lag gauge
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",partition="1",spring_id="kafkaConsumerFactory.csm-cloud-project-1",topic="csm_local_projectmanagement_project_delete",} 0.0
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-0",topic="csm_local_projectmanagement_project_delete",} 0.0
```

**UPDATE**: I updated again to Micrometer 1.5.3 and now the lag metrics are complete. However, the max lag metrics still do not contain the topic name just the regular lag metrics do.

```
# HELP kafka_consumer_fetch_manager_records_lag The latest lag of the partition
# TYPE kafka_consumer_fetch_manager_records_lag gauge
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-craft-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-0",topic="csm_local_referencedata_craft",} 0.0
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-user-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-user-0",topic="csm_local_usermanagement_user",} 0.0
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",partition="1",spring_id="kafkaConsumerFactory.csm-cloud-project-1",topic="csm_local_projectmanagement_project_delete",} 0.0
kafka_consumer_fetch_manager_records_lag{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-0",topic="csm_local_projectmanagement_project_delete",} 0.0
# HELP kafka_consumer_fetch_manager_records_lag_max The maximum lag in terms of number of records for any partition in this window
# TYPE kafka_consumer_fetch_manager_records_lag_max gauge
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-0",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-0",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-1",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-1",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-craft-2",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-2",} NaN
kafka_consumer_fetch_manager_records_lag_max{client_id="csm-cloud-project-user-0",kafka_version="5.4.2-ccs",spring_id="kafkaConsumerFactory.csm-cloud-project-user-0",} NaN
# HELP kafka_consumer_fetch_manager_records_lag_avg The average lag of the partition
# TYPE kafka_consumer_fetch_manager_records_lag_avg gauge
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-craft-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-craft-0",topic="csm_local_referencedata_craft",} NaN
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-user-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-user-0",topic="csm_local_usermanagement_user",} NaN
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-1",kafka_version="5.4.2-ccs",partition="1",spring_id="kafkaConsumerFactory.csm-cloud-project-1",topic="csm_local_projectmanagement_project_delete",} NaN
kafka_consumer_fetch_manager_records_lag_avg{client_id="csm-cloud-project-0",kafka_version="5.4.2-ccs",partition="0",spring_id="kafkaConsumerFactory.csm-cloud-project-0",topic="csm_local_projectmanagement_project_delete",} NaN

```

### PR DESCRIPTION
**Pull request by shakuzen**
This lead to many exceptions when using Prometheus with multiple Kafka client IDs and some meters with topic tags never being registered.

Resolves #2212

/cc @jeqo

### CODE REVIEW

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java [hunk 1]
```diff
@@ -155,11 +155,11 @@ void checkAndBindMetrics(MeterRegistry registry) {
                 for (Meter other : registry.find(meterName).meters()) {
                     List<Tag> tags = other.getId().getTags();
                     // Only consider meters from the same client before filtering
-                    if (differentClient(tags)) break;
+                    if (differentClient(tags, metric.metricName().tags().get(CLIENT_ID_TAG_NAME))) continue;
```
Comment (shakuzen) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java:158]: Previously this always used the same client ID for comparison, which wasn't correct. It also would break the loop if the client was different, but the meter with the same client could be returned after.

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java [hunk 2]
```diff
@@ -155,11 +155,11 @@ void checkAndBindMetrics(MeterRegistry registry) {
...
                     if (tags.size() < meterTagsWithCommonTags.size()) registry.remove(other);
                     // Check if already exists
                     else if (tags.size() == meterTagsWithCommonTags.size())
-                        if (tags.equals(meterTagsWithCommonTags)) return;
+                        if (tags.containsAll(meterTagsWithCommonTags) && meterTagsWithCommonTags.containsAll(tags)) return;
```
Comment (shakuzen) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java:162]: The `equals` method directly on the list objects would never return true, so an early return would never happen for this case, which I think isn't a big deal - it would just try registering a meter already registered, but this works around checking equality with this "clever hack".

**Review by shakuzen — COMMENTED** [review]
Just some comments explaining the changes. See also the test case that demonstrates the issue this fixes.

**Comment by shakuzen** [comment]
Additional testing shows there's still an issue not caught by the test because it does not have the limitation the Prometheus registry does. The issue is that it will remove one of the old meters and try to register the new one with more tags, but there is still another old meter (with a different client ID) registered, so it fails at that time. The logic would have to be updated to remove all registered meters with less tags and the same name, even if they have a different client ID. I'm trying to remember why we added the different client ID logic.

**Comment by shakuzen** [comment]
It looks like we don't need the skip different client ID logic since tests are passing, I updated the added test to behave as the PrometheusMeterRegistry does, and I have done an ad hoc test where I'm not seeing the errors anymore.

**Comment by izeye** [comment]
Looks good to me with an assumption that all clients have the same number of tags on the same metric.

When I was reading the different client logic, I imagined that the logic was necessary as a different client might have a different number of tags on the same metric. However, my assumption might be wrong as I have never tried it with a proper Kafka setup before. If it is wrong, we can close #2143 as it depends on the assumption.

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java (hunk 2 above)
Comment (izeye) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java:157]: It seems that the latter condition can be omitted as its outer `if` statement checks if they have the same size. I created https://github.com/micrometer-metrics/micrometer/pull/2313.
