### PR TITLE
Manual rollover of step meters for publishing partial step

### LINKED ISSUE #1882: Counters do not increment when ElasticMeterRegistry export is enabled
_Hi! Had posted this in Slack, but thought to report it here as well pending response there_

In short: I have a Spring Boot 2.2.5 application with `spring-boot-starter-actuator` and `micrometer-registry-elastic`; when I set `management.metrics.export.elastic.enabled=true`, then my counters do not increment anymore.

Not sure if this should be a micrometer issue or related to Spring Boot; `ElasticMeterRegistry` is in micrometer whereas `ElasticMetricsExportAutoConfiguration` is in Spring Boot. But since the latter seems to mostly delegate and is rather minimal otherwise, I thought to report it here first.

**To replicate the problem:**

1. Create a new project with: https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.2.5.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=actuator

2. Add a dependency on micrometer-registry-elastic
```
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-elastic</artifactId>
</dependency>
```

3. Create a test class containing

```java
@Test
void counterStaysAtZero() {
	DebugApplication.main("", "--management.metrics.export.elastic.enabled=true");
	// DebugApplication : Counter: 0.0 , [Measurement{statistic='COUNT', value=0.0}]
	// DebugApplication : Counter: 0.0 , [Measurement{statistic='COUNT', value=0.0}]
}
@Test
void counterAddsToOne() {
	DebugApplication.main("", "--management.metrics.export.elastic.enabled=false");
	// DebugApplication : Counter: 0.0 , [Measurement{statistic='COUNT', value=0.0}]
	// DebugApplication : Counter: 1.0 , [Measurement{statistic='COUNT', value=1.0}]
}
@SpringBootApplication
@RequiredArgsConstructor
@Slf4j
public static class DebugApplication implements ApplicationRunner {
	public static void main(String... args) {
		log.info("{}", args[1]);
		SpringApplication.run(DebugApplication.class, args).close();
	}
	private final MeterRegistry registry;
	@Override
	public void run(ApplicationArguments args) throws Exception {
		Counter counter = registry.counter("someCounter");
		log.info("Counter: {} , {}", counter.count(), counter.measure());
		counter.increment();
		log.info("Counter: {} , {}", counter.count(), counter.measure());
	}
}

If you then run both tests you will get the log output that's listed in each test method.

I would expect the Counter to increment regardless of whether metrics are exported; What can be done to make this so the counters increase?

### PR DESCRIPTION
**Pull request by shakuzen**
Allows step-based meters to manually be rolled over, instead of their normal time-based rollover. This is useful in the case of publishing a partial step, such as should happen on a final publish of step meters (including when an application is shutdown before a full step interval has happened). For now, we don't see a need to expose this API publicly, so we try to keep its visibility as low as possible and mark it as internal.

This approach was chosen because it is a non-invasive option with respect to implementations of StepMeterRegistry. The changes are isolated to core code we can update. This will fix the intended problem without requiring updates to every registry implementation (possibly including custom ones we do not maintain). It avoids messing with the clock and it (hopefully) avoids making the read behavior of step meters any more complex. 

Resolves #1882
Supersedes #3533

### CODE REVIEW

File: micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeter.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.micrometer.core.instrument.step;
+
+/**
+ * Internal. Intentionally package-private.
+ */
+interface StepMeter {
```
Comment (shakuzen) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeter.java:21]: This is internal (also package-private) so it is not the most important thing to bikeshed, but I'm beginning to wonder if a more specific name would be better. `ManualRolloverCapableStepMeter` is long but descriptive.

**Comment by lenin-jaganathan** [comment]
@shakuzen  Will this fix be back ported? If yes what are the versions for which we can expect this fix?

**Comment by lenin-jaganathan** [comment]
@shakuzen  Will this fix be back ported? If yes what are the versions for which we can expect this fix?

**Comment by shakuzen** [comment]
> Will this fix be back ported? If yes what are the versions for which we can expect this fix?

See my comment https://github.com/micrometer-metrics/micrometer/issues/1882#issuecomment-1467335481. Please do help by trying it out and letting us know if it works.

File: micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeterRegistry.java [hunk 2]
```diff
@@ -104,4 +104,14 @@ protected DistributionStatisticConfig defaultHistogramConfig() {
             .merge(DistributionStatisticConfig.DEFAULT);
     }
 
+    @Override
+    public void close() {
+        stop();
+        getMeters().stream()
+            .filter(meter -> meter instanceof StepMeter)
+            .map(meter -> (StepMeter) meter)
+            .forEach(StepMeter::_manualRollover);
```
Comment (lenin-jaganathan) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeterRegistry.java:113]: @shakuzen  I do have a concern with this particular close() method.

Scenario:
Assume that the step is 10 seconds and the application's graceful shutdown is initiated exactly or around 10th seconds. So, the scheduler would have already initiated the pushiSafely() and there are chances that close() is called around the same time. For a step meter, I believe there might be a scenario where manualRollover() will call sumThenReset() of StepValue and the pubishSafely initiated by Scheduler might call the rollCount(). This will again trigger a sumThenReset() which will make the data disappear or rest to zero.

Though this might be an edge case, registries with shorter step have more probability of running into this particular issue.

Comment (shakuzen) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepMeterRegistry.java:113]: Thanks for taking a look and giving feedback so quickly. I think the general scenario is summarized as the registry being closed during a scheduled publish. It does sound like some data can be lost then. Would you mind opening an issue for this so we don't forget? I'm not immediately sure what we'll want to do to mitigate this. I can take a closer look tomorrow. We should be able to write a test case that simulates this scenario.
