### PR TITLE
remove metrics from MeterRegistry when shutting down InstrumentedQueuedThreadPool

### LINKED ISSUE #4000: Remove metrics when shutting down InstrumentedQueuedThreadPool
remove metrics from MeterRegistry when shutting down InstrumentedQueuedThreadPool
Something like:

```java
    @Override
    protected void doStop() throws Exception {
       Set<Tag> tagSet = new HashSet<>();
        tags.forEach(tagSet::add);
        Stream.of("jetty.threads.config.min",
                        "jetty.threads.config.max",
                        "jetty.threads.busy",
                        "jetty.threads.jobs",
                        "jetty.threads.current",
                        "jetty.threads.idle")
                .flatMap(name -> meterRegistry.find(name).meters().stream())
                .map(Meter::getId)
                .filter(id -> new HashSet<>(id.getTags()).containsAll(tagSet))
                .forEach(meterRegistry::remove);
        super.doStop();
    }
```

**Rationale**
Clean up resources when not needed anymore

**Additional context**
The dropwizard metrics  jetty InstrumentedQueuedThreadPool does something [similar](https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedQueuedThreadPool.java#L103), and it seems like a good idea to do here as well.

I am happy to open a PR for this with tests if it is agreed that this should exist.

Thanks

### PR DESCRIPTION
**Pull request by wakingrufus**
remove metrics from MeterRegistry when shutting down  JettyServerThreadPoolMetrics/InstrumentedQueuedThreadPool

fixes #4000

### Rationale
Clean up resources when not needed anymore

### Additional context
The dropwizard metrics jetty InstrumentedQueuedThreadPool does something [similar](https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedQueuedThreadPool.java#L103), and it seems like a good idea to do here as well.

### CODE REVIEW

**Comment by wakingrufus** [comment]
Hi @shakuzen would you mind taking a look at this PR? Thanks

**Comment by wakingrufus** [comment]
@jonatan-ivanov I would really appreciate if someone could take a look at this PR. Thanks!
Sorry for the direct ping, but if I am going to ping someone random, I figured it might as well be someone who I have played duck bowling with ;)

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPool.java [hunk 1]
```diff
@@ -116,4 +120,18 @@ protected void doStart() throws Exception {
         threadPoolMetrics.bindTo(registry);
     }
 
+    @Override
+    protected void doStop() throws Exception {
+        Set<Tag> tagSet = new HashSet<>();
+        tags.forEach(tagSet::add);
+        Stream
+            .of("jetty.threads.config.min", "jetty.threads.config.max", "jetty.threads.busy", "jetty.threads.jobs",
+                    "jetty.threads.current", "jetty.threads.idle")
```
Comment (shakuzen) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPool.java:129]: I worry about keeping this list in sync with changes in `JettyServerThreadPoolMetrics`. It would be better to keep track of the metrics in `JettyServerThreadPoolMetrics` and make it `AutoCloseable`. Then `doStop` here just needs to close its instance of `JettyServerThreadPoolMetrics`. You can see an example of where we have done this in `KafkaMetrics`.

**Review by shakuzen — CHANGES_REQUESTED** [review]
Sorry for taking so long to review, and thanks for opening the pull request.

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java [hunk 2]
```diff
@@ -38,52 +44,81 @@
...
             .register(registry);
     }
 
+    @Override
+    public void close() throws Exception {
+        if (registry != null) {
+            Set<Tag> tagSet = new HashSet<>();
+            tags.forEach(tagSet::add);
+            Stream.of(MIN, MAX, BUSY, JOBS, CURRENT, IDLE)
+                .flatMap(name -> registry.find(name).meters().stream())
```
Comment (shakuzen) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:117]: This can fail to find the meters by name depending on the meter filters configured. That's why keeping a reference to the meters registered (or their `Id`) for directly removing them is the safe way to do this. See the implementation in `KafkaMetrics` for an example.

**Review by shakuzen — CHANGES_REQUESTED** [review]
Thank you for quickly updating the pull request. I've left another review.

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java (hunk 2 above)
Comment (wakingrufus) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:117]: Ah I see what you mean now. Thanks again, I will update this

Comment (wakingrufus) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java]: Ok, it is updated. Please take another look. Thanks again!

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java [hunk 3]
```diff
@@ -41,49 +46,80 @@
...
             .description("The number of idle threads in the pool")
             .tags(tags)
             .register(registry);
+        registeredMeterIds.add(idleGauge.getId());
+    }
+
+    @Override
+    public void close() throws Exception {
+        if (registry != null) {
+            registeredMeterIds.forEach(registry::remove);
```
Comment (jonatan-ivanov) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:121]: If we think that things will be reused and these meters need to be removed from the registry (reading the issue I'm still not sure or I missed something) we should definitely empty `registeredMeterIds` too.

File: micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java [hunk 4]
```diff
@@ -0,0 +1,103 @@
+/*
+ * Copyright 2019 VMware, Inc.
```
Comment (jonatan-ivanov) [inline micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java:2]: Should be 2024.
Could you please also update the year in other files too?

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java (hunk 3 above)
Comment (shakuzen) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:121]: I don't think it would be expected for an instance of `JettyServerThreadPoolMetrics` to be reused, though I suppose it is theoretically possible. In `InstrumentedQueuedThreadPool`, it will create a new instance in `doStart`.

Comment (wakingrufus) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:121]: I agree that an instance of JettyServerThreadPoolMetrics should not be reused, but emptying `registeredMeterIds` seems like a good idea just to avoid potential footguns. I'll make that change

File: micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java (hunk 4 above)
Comment (wakingrufus) [reply micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java:2]: Yes. is `VMware, Inc.` still the correct copyright holder?

File: micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+import java.util.Collections;
+import java.util.function.BiFunction;
+import java.util.stream.Collectors;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+class InstrumentedQueuedThreadPoolTest {
+
+    @Test
+    void test_metrics() throws Exception {
```
[the remark this answers is not in the document]
Comment (wakingrufus) [reply micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java]: Done. Thanks for the feedback!

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java (hunk 3 above)
Comment (wakingrufus) [reply micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyServerThreadPoolMetrics.java:121]: This is done

**Comment by wakingrufus** [comment]
I have made all requested changes. Please take another look.
Thanks again!

File: micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java (hunk 4 above)
Comment (shakuzen) [reply micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPoolTest.java]: Yes, thanks.

**Review by shakuzen — APPROVED** [review]

**Comment by shakuzen** [comment]
Thank you for the pull request and patience and all the quick turnarounds on feedback.
