### PR TITLE
Guard against ClassNotFoundException on GarbageCollectionNotificationInfo in GC metrics binder

### LINKED ISSUE #391: Guard against ClassNotFoundException in JvmGcMetrics
See https://github.com/spring-projects/spring-boot/issues/11879

### PR DESCRIPTION
**Pull request by vpavic**
This resolves #391.

The original fix (see 85d01ec) didn't work because `JvmGcMetrics` was registered as a bean in Spring Boot's config, and as such was subject to introspection. Since introspection also looks at private methods, and `JvmGcMetrics#isConcurrentPhase` had `GarbageCollectionNotificationInfo` in its signature which caused things to blow up before even reaching `JvmGcMetrics#bindTo`.

Additionally, I've added some logging to make users aware that GC notifications won't be available, rather than just swallowing `ClassNotFoundException`.

Also since `JvmGcMetrics#bindTo` gets hit quite a few times in Boot app, I've extracted guard to initialization phase to prevent multiple calls to `Class.forName` as well as multiple logging entries. Check itself is moved to (what it seems to me) a better place to prevent registration of multiple notification listeners that won't be doing anything due to `GarbageCollectionNotificationInfo` not being available.

Let me know what you think @jkschneider. I've tested this in WildFly 10.1 both in scenarios where `com.sun.management` is and is not available.

### CODE REVIEW

File: micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java [hunk 1]
```diff
@@ -120,23 +127,19 @@ public void bindTo(MeterRegistry registry) {
...
+            for (GarbageCollectorMXBean mbean : ManagementFactory.getGarbageCollectorMXBeans()) {
+                if (mbean instanceof NotificationEmitter) {
+                    ((NotificationEmitter) mbean).addNotificationListener((notification, ref) -> {
+                        final String type = notification.getType();
                         if (type.equals(GarbageCollectionNotificationInfo.GARBAGE_COLLECTION_NOTIFICATION)) {
                             CompositeData cd = (CompositeData) notification.getUserData();
                             GarbageCollectionNotificationInfo notificationInfo = GarbageCollectionNotificationInfo.from(cd);
 
-                            if (isConcurrentPhase(notificationInfo)) {
+                            if (isConcurrentPhase(notificationInfo.getGcCause())) {
```
Comment (jkschneider) [inline micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java]: Good catch! Thanks

**Comment by jkschneider** [comment]
Appreciate your time @vpavic. It was a big help in this last push toward 1.0 GA.
